### PR TITLE
👷 add windows runner

### PR DESCRIPTION
**Pull request by TimMikeladze**
make sure the tests pass on windows

**Intentions:**

- 👷 - Adding CI build system

**Areas:**

- add windows runner

### CODE REVIEW

**Comment by KyleScharnhorst** [comment]
duplicating my comment from other PR:

kinda pokin' at it right now, $(yarn bin jest) seems to work by itself.

$ $(yarn bin jest)
PASS tests/GitEmoji.test.ts
PASS tests/GitHub.test.ts

Test Suites: 2 passed, 2 total
Tests: 7 passed, 7 total
Snapshots: 6 passed, 6 total
Time: 4.065 s
Ran all test suites.

**Comment by KyleScharnhorst** [comment]
this works for me, not sure exactly what the implications of these changes are but yarn test produces what I would expect as good output:

diff --git a/jest.config.json b/jest.config.json
index 6888c52..b843bf6 100644
--- a/jest.config.json
+++ b/jest.config.json
@@ -4,6 +4,7 @@
   "testPathIgnorePatterns": ["<rootDir>/node_modules/"],
   "setupFiles": ["dotenv/config"],
   "testMatch": ["**/?(*.)+(spec|test).[jt]s?(x)"],
+  "extensionsToTreatAsEsm": [".ts"],
   "transform": {
     "^.+\\.tsx?$": [
       "ts-jest",
diff --git a/package.json b/package.json
index 767473f..7fa4822 100644
--- a/package.json
+++ b/package.json
@@ -28,7 +28,7 @@
     "commit": "yarn build -f modern && node dist/cli.modern.js",
     "build": "rm -rf dist && tsc && microbundle src/{index,cli}.ts --target node",
     "lint": "eslint --fix {src,__tests__}/**/*.ts && prettier --write .",
-    "test": "yarn node --experimental-vm-modules $(yarn bin jest) --coverage",
+    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js --coverage",
     "prepublishOnly": "yarn lint && yarn test && yarn build",
     "release": "release-it"
   },

yarn test output:

$ yarn test
yarn run v1.22.19
$ node --experimental-vm-modules node_modules/jest/bin/jest.js --coverage
(node:6040) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  __tests__/GitEmoji.test.ts
(node:17644) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  __tests__/GitHub.test.ts
---------------------------|---------|----------|---------|---------|-------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------------|---------|----------|---------|---------|-------------------
All files                  |   87.03 |    80.51 |   88.57 |    87.5 |                   
 CommitIt.ts               |   69.23 |       50 |      50 |   71.05 | 24-32,86,90-95    
 GitEmoji.ts               |     100 |      100 |     100 |     100 |                   
 GitHub.ts                 |     100 |       90 |     100 |     100 | 57                
 IntentionAndAreaPlugin.ts |   96.15 |    87.75 |     100 |   95.91 | 109,142           
 types.ts                  |     100 |      100 |     100 |     100 | 
---------------------------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   6 passed, 6 total
Time:        3.15 s
Ran all test suites.
Done in 4.13s.



Side note, uncovered lines 24-32 is the offending function from the PR.

**Comment by TimMikeladze** [comment]
@KyleScharnhorst success! Thank you!! 

https://github.com/TimMikeladze/commit-it/actions/runs/3922501856/jobs/6705485123

**Comment by KyleScharnhorst** [comment]
@TimMikeladze O hellll yeh 😄

**Pull request merged**
