### PR TITLE
🐛 Fix windows pathing issue.

### PR DESCRIPTION
**Pull request by KyleScharnhorst**
Seemed to be an issue in windows where 'import' wants a file URL and would get upset with drive prefixes ( e.g., "c:" ). In the function loadConfig, we're using path.resolve which returns an absolute path and isn't what import wants ultimately resulting in the issue. To fix we convert the raw path to the expected file URL.

Seems to still work on linux.

Also, not sure about the lock files.

**Intentions:**

- 🐛 - Bugfix

**Areas:**

- Fix windows pathing issue.

### CODE REVIEW

**Comment by TimMikeladze** [comment]
Thanks for the PR! 

This looks good, however the lock files need to be excluded.

**Comment by TimMikeladze** [comment]
@KyleScharnhorst When your run `yarn test` locally on your windows machine, do all the test pass?

I created https://github.com/TimMikeladze/commit-it/pull/7 which adds a windows runner to the CI workflow so the tests run on both linux and windows. 

Looking at the logs of that run, It looks like all the tests can't even be started on windows due to an error.

https://github.com/TimMikeladze/commit-it/actions/runs/3921169845/jobs/6703289023

**Comment by KyleScharnhorst** [comment]
lock files karate chopped

it's definitely upset with the test command, unsure what it is atm. Maybe something around the "$(" syntax.

$ yarn test
yarn run v1.22.19
$ yarn node --experimental-vm-modules $(yarn bin jest) --coverage
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'C:\Users\kyles\Git\commit-it\$(yarn'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: --experimental-vm-modules $(yarn bin jest) --coverage
Directory: C:\Users\kyles\Git\commit-it
Output:

info Visit https://yarnpkg.com/en/docs/cli/node for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by TimMikeladze** [comment]
Great! Thanks for the contribution. Will merge and publish a new release shortly. 

It would be awesome if you could help with figuring out the windows test issue on #7 if you have some time later. Not having a windows machine will make debugging this for me a pain in the butt.

**Comment by KyleScharnhorst** [comment]
kinda pokin' at it right now, $(yarn bin jest) seems to work by itself.

$ $(yarn bin jest)
 PASS  __tests__/GitEmoji.test.ts
 PASS  __tests__/GitHub.test.ts    

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   6 passed, 6 total
Time:        4.065 s
Ran all test suites.

**Pull request merged**
